# Serves the static report generated by report.py (index.html/tickers.html)
# for local viewing. Not part of the trading system's own deployment --
# report/ is regenerated on demand (`python report.py`) and gitignored;
# rebuild this image after regenerating to pick up new content.
FROM nginx:alpine
COPY report/ /usr/share/nginx/html/
EXPOSE 80
